5gcamflow-1:
	mkdir -p ~/ds/camflow/10-05-2024/base
	mkdir -p ~/ds/camflow/10-05-2024/stream
	number=80 ; while [ $$number -le 84 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/8/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-2:
	number=85 ; while [ $$number -le 89 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/8/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-3:
	number=90 ; while [ $$number -le 94 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/9/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-4:
	number=95 ; while [ $$number -le 99 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/9/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-5:
	number=20 ; while [ $$number -le 24 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/2/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-6:
	number=25 ; while [ $$number -le 29 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/2/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-7:
	number=30 ; while [ $$number -le 34 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/3/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-8:
	number=35 ; while [ $$number -le 39 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/3/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-9:
	number=40 ; while [ $$number -le 44 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/4/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-0:
	number=45 ; while [ $$number -le 49 ] ; do \
		python prepare.py -i ~/ds/camflow/10-05-2024/split/4/$$number.txt -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/10-05-2024/base/base-$$number.txt -S ~/ds/camflow/10-05-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-11:
	number=50 ; while [ $$number -le 54 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-12:
	number=55 ; while [ $$number -le 59 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-13:
	number=60 ; while [ $$number -le 65 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

unicorn-camflow:
	number=0 ; while [ $$number -le 9 ] ; do \
		python parse.py -i ~/ds/unicorn/raw/$$number.txt -B ~/ds/unicorn/raw/base/base-$$number.txt -S ~/ds/unicorn/raw/stream/stream-$$number.txt ; \
		number=`expr $$number + 1` ; \
	done